# V3.2 CDP metadata sensor. No headers/cookies/bodies; query and fragment removed.
function ConvertTo-RedactedUrl{param([string]$Url);try{$u=[Uri]$Url;$b=[UriBuilder]::new($u);$b.Query="";$b.Fragment="";$b.Uri.AbsoluteUri}catch{$Url}}
function Invoke-CdpCapture{[CmdletBinding()]param([Parameter(Mandatory)][int]$Port,[Parameter(Mandatory)][string]$OutFile,[Parameter(Mandatory)][string]$Label,[int]$Seconds=60)
 if(Test-Path $OutFile){Remove-Item $OutFile -Force};$deadline=(Get-Date).AddSeconds($Seconds);$page=$null
 while(-not $page -and (Get-Date)-lt $deadline){try{$ts=@(Invoke-RestMethod "http://127.0.0.1:$Port/json/list" -TimeoutSec 2);$page=$ts|Where-Object type -eq page|Select-Object -First 1}catch{};if(-not $page){Start-Sleep -Milliseconds 250}}
 if(-not $page){throw "[$Label] no CDP page target on $Port"};$ws=[Net.WebSockets.ClientWebSocket]::new();$cc=[Threading.CancellationTokenSource]::new();$cc.CancelAfter(5000)
 try{$ws.ConnectAsync([Uri]$page.webSocketDebuggerUrl,$cc.Token).GetAwaiter().GetResult()}finally{$cc.Dispose()}
 $en=[Text.Encoding]::UTF8.GetBytes((@{id=1;method="Network.enable"}|ConvertTo-Json -Compress));$ws.SendAsync([ArraySegment[byte]]::new($en),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult()
 Write-Host "[$Label] attached target=$($page.id) $($page.url)" -ForegroundColor Green;$buf=New-Object byte[] 65536;$count=0
 try{while((Get-Date)-lt $deadline -and $ws.State -eq [Net.WebSockets.WebSocketState]::Open){$remain=[int][Math]::Max(1,($deadline-(Get-Date)).TotalMilliseconds);$rc=[Threading.CancellationTokenSource]::new();$rc.CancelAfter($remain);$ms=[IO.MemoryStream]::new()
  try{do{$res=$ws.ReceiveAsync([ArraySegment[byte]]::new($buf),$rc.Token).GetAwaiter().GetResult();if($res.MessageType -eq [Net.WebSockets.WebSocketMessageType]::Close){return};if($res.Count){$ms.Write($buf,0,$res.Count)};if($ms.Length -gt 4194304){throw "CDP message >4MiB"}}while(-not $res.EndOfMessage)}catch [OperationCanceledException]{break}finally{$rc.Dispose()}
  try{$o=[Text.Encoding]::UTF8.GetString($ms.ToArray())|ConvertFrom-Json}catch{continue}finally{$ms.Dispose()};if($o.method -ne "Network.responseReceived"){continue};$p=$o.params;$r=$p.response;if(-not $r.remoteIPAddress){continue}
  $url=ConvertTo-RedactedUrl ([string]$r.url);$hostName="-";try{$hostName=([Uri]$r.url).Host}catch{};$rec=[ordered]@{timestamp=(Get-Date).ToUniversalTime().ToString("o");source=$Label;debugPort=$Port;targetId=[string]$page.id;targetUrl=ConvertTo-RedactedUrl([string]$page.url);requestId=[string]$p.requestId;resourceType=[string]$p.type;url=$url;host=$hostName;status=$r.status;mimeType=[string]$r.mimeType;protocol=[string]$r.protocol;remoteIP=[string]$r.remoteIPAddress;remotePort=[int]$r.remotePort;evidenceClass="OBSERVED_BROWSER";capturePolicy="METADATA_ONLY"};($rec|ConvertTo-Json -Compress)|Add-Content $OutFile -Encoding UTF8;$count++;Write-Host "[$Label] $($r.status) $($r.remoteIPAddress):$($r.remotePort) $url"}}
 }finally{try{$ws.Dispose()}catch{};Write-Host "[$Label] capture ended. events=$count" -ForegroundColor DarkGray}
}
