"""
Machine Observer V0.6.1

Evidence architecture:

REAL SYSTEM
    |
    +-- Process / PID / Command line
    +-- TCP socket observations
    +-- Windows DNS cache
    +-- PTR contextual enrichment
    |
    +-- Optional active TLS/HTTP probes
    |
    v
SQLite Evidence Store
    |
    v
Activity Correlator
    |
    v
"What is this computer doing?"

Evidence classes:

OBSERVED
    Direct local evidence.

CORRELATED
    Association supported by other evidence, such as DNS.

INFERRED
    Interpretation generated from observed/correlated evidence.

PROBED
    A new connection deliberately generated by MachineObserver.

UNKNOWN
    Evidence is insufficient.

IMPORTANT:
- HTTPS payloads are NOT decrypted.
- PTR is NOT treated as proof of the hostname used by an application.
- TLS/HTTP probes are stored separately from observed application traffic.
- Initial sockets are BASELINE, not falsely labelled OPEN.
- A socket disappearing from a polling snapshot is DISAPPEARED,
  not claimed to be an exact TCP FIN/RST event.
"""

import hashlib
import http.client
import ipaddress
import json
import signal
import socket
import sqlite3
import ssl
import subprocess
import threading
import time
import uuid

from collections import defaultdict
from datetime import datetime, timezone

try:
    import psutil
except ImportError:
    print("psutil is required.")
    print("Install with:")
    print("py -m pip install psutil")
    raise SystemExit(1)


# ============================================================
# CONFIGURATION
# ============================================================

VERSION = "0.6.1"

DB_PATH = "observer.db"

POLL_SECONDS = 0.25
DNS_REFRESH_SECONDS = 3.0
REPORT_INTERVAL_SECONDS = 30.0

# Active probes generate NEW traffic.
# Keep True for experimentation.
# Set False for a purely passive observer.
ACTIVE_PROBES = True

TLS_PROBE_ENABLED = True
HTTP_PROBE_ENABLED = True

PROBE_TIMEOUT = 4

MAX_TLS_PROBES = 20
MAX_HTTP_PROBES = 20


# ============================================================
# GLOBAL STATE
# ============================================================

running = True

active_flows = {}

dns_map = {}

dns_snapshot = set()

tls_probed = set()
http_probed = set()

probe_lock = threading.Lock()
db_lock = threading.RLock()

SESSION_ID = str(uuid.uuid4())
SESSION_STARTED = None


# ============================================================
# TIME
# ============================================================

def utc_now():

    return datetime.now(
        timezone.utc
    ).isoformat(
        timespec="milliseconds"
    )


# ============================================================
# DATABASE CONNECTION
# ============================================================

db = sqlite3.connect(
    DB_PATH,
    check_same_thread=False
)

db.row_factory = sqlite3.Row

db.execute(
    "PRAGMA journal_mode=WAL"
)

db.execute(
    "PRAGMA synchronous=NORMAL"
)


# ============================================================
# DATABASE HELPERS
# ============================================================

def db_execute(sql, params=()):

    with db_lock:

        cursor = db.execute(
            sql,
            params
        )

        db.commit()

        return cursor


def table_exists(name):

    row = db.execute(
        """
        SELECT 1
        FROM sqlite_master
        WHERE type='table'
          AND name=?
        """,
        (name,)
    ).fetchone()

    return row is not None


def table_columns(name):

    if not table_exists(name):
        return set()

    rows = db.execute(
        f'PRAGMA table_info("{name}")'
    ).fetchall()

    return {
        row[1]
        for row in rows
    }


def unique_legacy_name(base):

    candidate = base
    counter = 1

    while table_exists(candidate):

        candidate = (
            f"{base}_{counter}"
        )

        counter += 1

    return candidate


def preserve_if_incompatible(
    table,
    required_columns,
    legacy_base
):

    columns = table_columns(table)

    if not columns:
        return

    missing = (
        set(required_columns)
        - columns
    )

    if not missing:
        return

    destination = (
        unique_legacy_name(
            legacy_base
        )
    )

    print()
    print(
        f"MIGRATION: old '{table}' schema detected."
    )

    print(
        "Missing columns:",
        ", ".join(
            sorted(missing)
        )
    )

    print(
        f"Preserving it as '{destination}'."
    )

    db.execute(
        f'ALTER TABLE "{table}" '
        f'RENAME TO "{destination}"'
    )

    db.commit()


# ============================================================
# AUTOMATIC DATABASE MIGRATION
# ============================================================

def migrate_database():

    print(
        "Checking database schema..."
    )

    preserve_if_incompatible(
        "flows",
        {
            "flow_id",
            "session_id",
            "first_seen",
            "last_seen",
            "status",
            "close_semantics",
            "protocol",
            "pid",
            "process",
            "cmdline",
            "local_ip",
            "local_port",
            "remote_ip",
            "remote_port",
            "forward_names",
            "reverse_name",
            "evidence_confidence"
        },
        "flows_legacy"
    )

    preserve_if_incompatible(
        "dns_evidence",
        {
            "session_id",
            "observed_at",
            "hostname",
            "address",
            "ttl",
            "expires_at",
            "source"
        },
        "dns_evidence_legacy"
    )

    preserve_if_incompatible(
        "probes",
        {
            "session_id",
            "observed_at",
            "probe_type",
            "remote_ip",
            "remote_port",
            "hostname_candidate",
            "result",
            "source"
        },
        "probes_legacy"
    )

    preserve_if_incompatible(
        "activities",
        {
            "session_id",
            "generated_at",
            "category",
            "meaning",
            "flow_count",
            "evidence_class"
        },
        "activities_legacy"
    )

    print(
        "Database schema check complete."
    )


# ============================================================
# CREATE CURRENT DATABASE SCHEMA
# ============================================================

def init_database():

    with db_lock:

        db.executescript(
            """
            CREATE TABLE IF NOT EXISTS schema_meta
            (
                key TEXT PRIMARY KEY,
                value TEXT
            );


            CREATE TABLE IF NOT EXISTS sessions
            (
                session_id TEXT PRIMARY KEY,

                started_at TEXT NOT NULL,

                stopped_at TEXT,

                version TEXT NOT NULL
            );


            CREATE TABLE IF NOT EXISTS flows
            (
                id INTEGER PRIMARY KEY AUTOINCREMENT,

                flow_id TEXT UNIQUE NOT NULL,

                session_id TEXT NOT NULL,

                first_seen TEXT NOT NULL,

                last_seen TEXT NOT NULL,

                status TEXT NOT NULL,

                close_semantics TEXT,

                protocol TEXT NOT NULL,

                pid INTEGER,

                process TEXT,

                cmdline TEXT,

                local_ip TEXT,

                local_port INTEGER,

                remote_ip TEXT,

                remote_port INTEGER,

                forward_names TEXT,

                reverse_name TEXT,

                process_observed INTEGER DEFAULT 0,

                socket_observed INTEGER DEFAULT 0,

                forward_dns_observed INTEGER DEFAULT 0,

                reverse_dns_observed INTEGER DEFAULT 0,

                evidence_confidence REAL DEFAULT 0.0
            );


            CREATE TABLE IF NOT EXISTS dns_evidence
            (
                id INTEGER PRIMARY KEY AUTOINCREMENT,

                session_id TEXT NOT NULL,

                observed_at TEXT NOT NULL,

                hostname TEXT NOT NULL,

                address TEXT NOT NULL,

                ttl INTEGER,

                expires_at REAL,

                source TEXT NOT NULL
            );


            CREATE TABLE IF NOT EXISTS probes
            (
                id INTEGER PRIMARY KEY AUTOINCREMENT,

                session_id TEXT NOT NULL,

                observed_at TEXT NOT NULL,

                probe_type TEXT NOT NULL,

                remote_ip TEXT NOT NULL,

                remote_port INTEGER NOT NULL,

                hostname_candidate TEXT,

                result TEXT,

                source TEXT NOT NULL
            );


            CREATE TABLE IF NOT EXISTS activities
            (
                id INTEGER PRIMARY KEY AUTOINCREMENT,

                session_id TEXT NOT NULL,

                generated_at TEXT NOT NULL,

                category TEXT NOT NULL,

                meaning TEXT NOT NULL,

                process TEXT,

                pid INTEGER,

                flow_count INTEGER,

                hostnames TEXT,

                remote_ips TEXT,

                evidence_confidence REAL,

                classification_confidence REAL,

                evidence_class TEXT
            );


            CREATE INDEX IF NOT EXISTS
            idx_flows_session
            ON flows(session_id);


            CREATE INDEX IF NOT EXISTS
            idx_flows_remote
            ON flows(remote_ip, remote_port);


            CREATE INDEX IF NOT EXISTS
            idx_flows_pid
            ON flows(pid);


            CREATE INDEX IF NOT EXISTS
            idx_dns_address
            ON dns_evidence(address);


            CREATE INDEX IF NOT EXISTS
            idx_dns_hostname
            ON dns_evidence(hostname);


            CREATE INDEX IF NOT EXISTS
            idx_probes_remote
            ON probes(remote_ip, remote_port);
            """
        )

        db.execute(
            """
            INSERT INTO schema_meta
            (
                key,
                value
            )
            VALUES
            (
                'schema_version',
                ?
            )

            ON CONFLICT(key)
            DO UPDATE SET
                value=excluded.value
            """,
            (VERSION,)
        )

        db.commit()


# ============================================================
# SESSION MANAGEMENT
# ============================================================

def start_session():

    global SESSION_STARTED

    SESSION_STARTED = utc_now()

    db_execute(
        """
        INSERT INTO sessions
        (
            session_id,
            started_at,
            version
        )
        VALUES (?, ?, ?)
        """,
        (
            SESSION_ID,
            SESSION_STARTED,
            VERSION
        )
    )


# ============================================================
# PROCESS SENSOR
# ============================================================

def get_process_info(pid):

    try:

        process = psutil.Process(pid)

        name = process.name()

        try:

            cmdline = " ".join(
                process.cmdline()
            )

        except Exception:

            cmdline = None

        return {
            "name": name,
            "cmdline": cmdline,
            "observed": True
        }

    except Exception:

        return {
            "name": "unknown",
            "cmdline": None,
            "observed": False
        }


# ============================================================
# IP HELPERS
# ============================================================

def is_ip(value):

    try:

        ipaddress.ip_address(
            value
        )

        return True

    except Exception:

        return False


def safe_for_active_probe(ip):

    try:

        address = (
            ipaddress.ip_address(ip)
        )

    except Exception:

        return False

    if address.is_loopback:
        return False

    if address.is_link_local:
        return False

    if address.is_multicast:
        return False

    if address.is_unspecified:
        return False

    if address.is_private:
        return False

    return True


# ============================================================
# WINDOWS DNS CACHE
# ============================================================

def read_dns_cache():

    script = r"""
$ErrorActionPreference = 'SilentlyContinue'

Get-DnsClientCache |
Where-Object {
    $_.Entry -and $_.Data
} |
ForEach-Object {

    [PSCustomObject]@{

        Name = $_.Entry

        Data = $_.Data

        TTL = $_.TimeToLive
    }

} |
ConvertTo-Json -Compress
"""

    try:

        result = subprocess.run(
            [
                "powershell.exe",
                "-NoProfile",
                "-Command",
                script
            ],
            capture_output=True,
            text=True,
            timeout=5
        )

    except Exception:

        return []

    raw = result.stdout.strip()

    if not raw:
        return []

    try:

        records = json.loads(
            raw
        )

    except Exception:

        return []

    if isinstance(
        records,
        dict
    ):

        records = [
            records
        ]

    return records


def refresh_dns_cache():

    global dns_map
    global dns_snapshot

    records = read_dns_cache()

    current_map = defaultdict(
        set
    )

    current_snapshot = set()

    observed = utc_now()

    current_epoch = time.time()


    for record in records:

        hostname = str(
            record.get("Name")
            or ""
        ).strip().rstrip(".")


        address = str(
            record.get("Data")
            or ""
        ).strip()


        if not hostname:
            continue

        if not address:
            continue

        # Ignore CNAME values here.
        # They will become their own graph sensor later.
        if not is_ip(address):
            continue


        try:

            ttl = int(
                record.get("TTL")
                or 0
            )

        except Exception:

            ttl = 0


        current_map[
            address
        ].add(
            hostname
        )


        evidence_key = (
            hostname.lower(),
            address
        )


        current_snapshot.add(
            evidence_key
        )


        # Only insert when a hostname/IP pair
        # appears for the first time in the
        # current in-memory observation state.
        if evidence_key not in dns_snapshot:

            db_execute(
                """
                INSERT INTO dns_evidence
                (
                    session_id,
                    observed_at,
                    hostname,
                    address,
                    ttl,
                    expires_at,
                    source
                )
                VALUES
                (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    SESSION_ID,
                    observed,
                    hostname,
                    address,
                    ttl,
                    current_epoch + ttl,
                    "WINDOWS_DNS_CACHE"
                )
            )


    dns_snapshot = (
        current_snapshot
    )

    dns_map = {
        ip: set(names)
        for ip, names
        in current_map.items()
    }


# ============================================================
# PTR CONTEXT
# ============================================================

ptr_cache = {}


def reverse_dns_worker(ip):

    if ip in ptr_cache:
        return

    try:

        name = socket.gethostbyaddr(
            ip
        )[0].rstrip(".")

    except Exception:

        name = None

    ptr_cache[
        ip
    ] = name


def get_ptr_without_blocking(ip):

    if ip in ptr_cache:

        return (
            ptr_cache[ip],
            ptr_cache[ip] is not None
        )


    # Critical:
    # Never block the 250 ms socket loop
    # waiting for DNS/PTR.
    threading.Thread(
        target=reverse_dns_worker,
        args=(ip,),
        daemon=True
    ).start()


    return (
        None,
        False
    )


# ============================================================
# EVIDENCE SCORE
# ============================================================

def evidence_score(
    process_observed,
    socket_observed,
    forward_dns_observed
):

    score = 0.0

    if process_observed:
        score += 0.35

    if socket_observed:
        score += 0.40

    if forward_dns_observed:
        score += 0.25

    # PTR intentionally contributes nothing.

    return round(
        min(
            score,
            1.0
        ),
        2
    )


# ============================================================
# TLS ACTIVE PROBE
# ============================================================

def tls_probe(
    ip,
    port,
    hostname
):

    if not ACTIVE_PROBES:
        return

    if not TLS_PROBE_ENABLED:
        return

    if port != 443:
        return

    if not safe_for_active_probe(
        ip
    ):
        return


    key = (
        ip,
        port,
        hostname
    )


    with probe_lock:

        if key in tls_probed:
            return

        if (
            len(tls_probed)
            >= MAX_TLS_PROBES
        ):
            return

        tls_probed.add(
            key
        )


    server_name = (
        hostname
        if hostname
        else ip
    )


    try:

        context = (
            ssl.create_default_context()