"""
Machine Observer V0.6.1

Evidence architecture:

REAL SYSTEM
    |
    +-- Process / PID / Command line
    +-- TCP socket observations
    +-- Windows DNS cache
    +-- PTR contextual enrichment
    |
    +-- Optional active TLS/HTTP probes
    |
    v
SQLite Evidence Store
    |
    v
Activity Correlator
    |
    v
"What is this computer doing?"

Evidence classes:

OBSERVED
    Direct local evidence.

CORRELATED
    Association supported by other evidence, such as DNS.

INFERRED
    Interpretation generated from observed/correlated evidence.

PROBED
    A new connection deliberately generated by MachineObserver.

UNKNOWN
    Evidence is insufficient.

IMPORTANT:
- HTTPS payloads are NOT decrypted.
- PTR is NOT treated as proof of the hostname used by an application.
- TLS/HTTP probes are stored separately from observed application traffic.
- Initial sockets are BASELINE, not falsely labelled OPEN.
- A socket disappearing from a polling snapshot is DISAPPEARED,
  not claimed to be an exact TCP FIN/RST event.
"""

import hashlib
import http.client
import ipaddress
import json
import signal
import socket
import sqlite3
import ssl
import subprocess
import threading
import time
import uuid

from collections import defaultdict
from datetime import datetime, timezone

try:
    import psutil
except ImportError:
    print("psutil is required.")
    print("Install with:")
    print("py -m pip install psutil")
    raise SystemExit(1)


# ============================================================
# CONFIGURATION
# ============================================================

VERSION = "0.6.1"

DB_PATH = "observer.db"

POLL_SECONDS = 0.25
DNS_REFRESH_SECONDS = 3.0
REPORT_INTERVAL_SECONDS = 30.0

# Active probes generate NEW traffic.
# Keep True for experimentation.
# Set False for a purely passive observer.
ACTIVE_PROBES = True

TLS_PROBE_ENABLED = True
HTTP_PROBE_ENABLED = True

PROBE_TIMEOUT = 4

MAX_TLS_PROBES = 20
MAX_HTTP_PROBES = 20


# ============================================================
# GLOBAL STATE
# ============================================================

running = True

active_flows = {}

dns_map = {}

dns_snapshot = set()

tls_probed = set()
http_probed = set()

probe_lock = threading.Lock()
db_lock = threading.RLock()

SESSION_ID = str(uuid.uuid4())
SESSION_STARTED = None


# ============================================================
# TIME
# ============================================================

def utc_now():

    return datetime.now(
        timezone.utc
    ).isoformat(
        timespec="milliseconds"
    )


# ============================================================
# DATABASE CONNECTION
# ============================================================

db = sqlite3.connect(
    DB_PATH,
    check_same_thread=False
)

db.row_factory = sqlite3.Row

db.execute(
    "PRAGMA journal_mode=WAL"
)

db.execute(
    "PRAGMA synchronous=NORMAL"
)


# ============================================================
# DATABASE HELPERS
# ============================================================

def db_execute(sql, params=()):

    with db_lock:

        cursor = db.execute(
            sql,
            params
        )

        db.commit()

        return cursor


def table_exists(name):

    row = db.execute(
        """
        SELECT 1
        FROM sqlite_master
        WHERE type='table'
          AND name=?
        """,
        (name,)
    ).fetchone()

    return row is not None


def table_columns(name):

    if not table_exists(name):
        return set()

    rows = db.execute(
        f'PRAGMA table_info("{name}")'
    ).fetchall()

    return {
        row[1]
        for row in rows
    }


def unique_legacy_name(base):

    candidate = base
    counter = 1

    while table_exists(candidate):

        candidate = (
            f"{base}_{counter}"
        )

        counter += 1

    return candidate


def preserve_if_incompatible(
    table,
    required_columns,
    legacy_base
):

    columns = table_columns(table)

    if not columns:
        return

    missing = (
        set(required_columns)
        - columns
    )

    if not missing:
        return

    destination = (
        unique_legacy_name(
            legacy_base
        )
    )

    print()
    print(
        f"MIGRATION: old '{table}' schema detected."
    )

    print(
        "Missing columns:",
        ", ".join(
            sorted(missing)
        )
    )

    print(
        f"Preserving it as '{destination}'."
    )

    db.execute(
        f'ALTER TABLE "{table}" '
        f'RENAME TO "{destination}"'
    )

    db.commit()


# ============================================================
# AUTOMATIC DATABASE MIGRATION
# ============================================================

def migrate_database():

    print(
        "Checking database schema..."
    )

    preserve_if_incompatible(
        "flows",
        {
            "flow_id",
            "session_id",
            "first_seen",
            "last_seen",
            "status",
            "close_semantics",
            "protocol",
            "pid",
            "process",
            "cmdline",
            "local_ip",
            "local_port",
            "remote_ip",
            "remote_port",
            "forward_names",
            "reverse_name",
            "evidence_confidence"
        },
        "flows_legacy"
    )

    preserve_if_incompatible(
        "dns_evidence",
        {
            "session_id",
            "observed_at",
            "hostname",
            "address",
            "ttl",
            "expires_at",
            "source"
        },
        "dns_evidence_legacy"
    )

    preserve_if_incompatible(
        "probes",
        {
            "session_id",
            "observed_at",
            "probe_type",
            "remote_ip",
            "remote_port",
            "hostname_candidate",
            "result",
            "source"
        },
        "probes_legacy"
    )

    preserve_if_incompatible(
        "activities",
        {
            "session_id",
            "generated_at",
            "category",
            "meaning",
            "flow_count",
            "evidence_class"
        },
        "activities_legacy"
    )

    print(
        "Database schema check complete."
    )


# ============================================================
# CREATE CURRENT DATABASE SCHEMA
# ============================================================

def init_database():

    with db_lock:

        db.executescript(
            """
            CREATE TABLE IF NOT EXISTS schema_meta
            (
                key TEXT PRIMARY KEY,
                value TEXT
            );


            CREATE TABLE IF NOT EXISTS sessions
            (
                session_id TEXT PRIMARY KEY,

                started_at TEXT NOT NULL,

                stopped_at TEXT,

                version TEXT NOT NULL
            );


            CREATE TABLE IF NOT EXISTS flows
            (
                id INTEGER PRIMARY KEY AUTOINCREMENT,

                flow_id TEXT UNIQUE NOT NULL,

                session_id TEXT NOT NULL,

                first_seen TEXT NOT NULL,

                last_seen TEXT NOT NULL,

                status TEXT NOT NULL,

                close_semantics TEXT,

                protocol TEXT NOT NULL,

                pid INTEGER,

                process TEXT,

                cmdline TEXT,

                local_ip TEXT,

                local_port INTEGER,

                remote_ip TEXT,

                remote_port INTEGER,

                forward_names TEXT,

                reverse_name TEXT,

                process_observed INTEGER DEFAULT 0,

                socket_observed INTEGER DEFAULT 0,

                forward_dns_observed INTEGER DEFAULT 0,

                reverse_dns_observed INTEGER DEFAULT 0,

                evidence_confidence REAL DEFAULT 0.0
            );


            CREATE TABLE IF NOT EXISTS dns_evidence
            (
                id INTEGER PRIMARY KEY AUTOINCREMENT,

                session_id TEXT NOT NULL,

                observed_at TEXT NOT NULL,

                hostname TEXT NOT NULL,

                address TEXT NOT NULL,

                ttl INTEGER,

                expires_at REAL,

                source TEXT NOT NULL
            );


            CREATE TABLE IF NOT EXISTS probes
            (
                id INTEGER PRIMARY KEY AUTOINCREMENT,

                session_id TEXT NOT NULL,

                observed_at TEXT NOT NULL,

                probe_type TEXT NOT NULL,

                remote_ip TEXT NOT NULL,

                remote_port INTEGER NOT NULL,

                hostname_candidate TEXT,

                result TEXT,

                source TEXT NOT NULL
            );


            CREATE TABLE IF NOT EXISTS activities
            (
                id INTEGER PRIMARY KEY AUTOINCREMENT,

                session_id TEXT NOT NULL,

                generated_at TEXT NOT NULL,

                category TEXT NOT NULL,

                meaning TEXT NOT NULL,

                process TEXT,

                pid INTEGER,

                flow_count INTEGER,

                hostnames TEXT,

                remote_ips TEXT,

                evidence_confidence REAL,

                classification_confidence REAL,

                evidence_class TEXT
            );


            CREATE INDEX IF NOT EXISTS
            idx_flows_session
            ON flows(session_id);


            CREATE INDEX IF NOT EXISTS
            idx_flows_remote
            ON flows(remote_ip, remote_port);


            CREATE INDEX IF NOT EXISTS
            idx_flows_pid
            ON flows(pid);


            CREATE INDEX IF NOT EXISTS
            idx_dns_address
            ON dns_evidence(address);


            CREATE INDEX IF NOT EXISTS
            idx_dns_hostname
            ON dns_evidence(hostname);


            CREATE INDEX IF NOT EXISTS
            idx_probes_remote
            ON probes(remote_ip, remote_port);
            """
        )

        db.execute(
            """
            INSERT INTO schema_meta
            (
                key,
                value
            )
            VALUES
            (
                'schema_version',
                ?
            )

            ON CONFLICT(key)
            DO UPDATE SET
                value=excluded.value
            """,
            (VERSION,)
        )

        db.commit()


# ============================================================
# SESSION MANAGEMENT
# ============================================================

def start_session():

    global SESSION_STARTED

    SESSION_STARTED = utc_now()

    db_execute(
        """
        INSERT INTO sessions
        (
            session_id,
            started_at,
            version
        )
        VALUES (?, ?, ?)
        """,
        (
            SESSION_ID,
            SESSION_STARTED,
            VERSION
        )
    )


# ============================================================
# PROCESS SENSOR
# ============================================================

def get_process_info(pid):

    try:

        process = psutil.Process(pid)

        name = process.name()

        try:

            cmdline = " ".join(
                process.cmdline()
            )

        except Exception:

            cmdline = None

        return {
            "name": name,
            "cmdline": cmdline,
            "observed": True
        }

    except Exception:

        return {
            "name": "unknown",
            "cmdline": None,
            "observed": False
        }


# ============================================================
# IP HELPERS
# ============================================================

def is_ip(value):

    try:

        ipaddress.ip_address(
            value
        )

        return True

    except Exception:

        return False


def safe_for_active_probe(ip):

    try:

        address = (
            ipaddress.ip_address(ip)
        )

    except Exception:

        return False

    if address.is_loopback:
        return False

    if address.is_link_local:
        return False

    if address.is_multicast:
        return False

    if address.is_unspecified:
        return False

    if address.is_private:
        return False

    return True


# ============================================================
# WINDOWS DNS CACHE
# ============================================================

def read_dns_cache():

    script = r"""
$ErrorActionPreference = 'SilentlyContinue'

Get-DnsClientCache |
Where-Object {
    $_.Entry -and $_.Data
} |
ForEach-Object {

    [PSCustomObject]@{

        Name = $_.Entry

        Data = $_.Data

        TTL = $_.TimeToLive
    }

} |
ConvertTo-Json -Compress
"""

    try:

        result = subprocess.run(
            [
                "powershell.exe",
                "-NoProfile",
                "-Command",
                script
            ],
            capture_output=True,
            text=True,
            timeout=5
        )

    except Exception:

        return []

    raw = result.stdout.strip()

    if not raw:
        return []

    try:

        records = json.loads(
            raw
        )

    except Exception:

        return []

    if isinstance(
        records,
        dict
    ):

        records = [
            records
        ]

    return records


def refresh_dns_cache():

    global dns_map
    global dns_snapshot

    records = read_dns_cache()

    current_map = defaultdict(
        set
    )

    current_snapshot = set()

    observed = utc_now()

    current_epoch = time.time()


    for record in records:

        hostname = str(
            record.get("Name")
            or ""
        ).strip().rstrip(".")


        address = str(
            record.get("Data")
            or ""
        ).strip()


        if not hostname:
            continue

        if not address:
            continue

        # Ignore CNAME values here.
        # They will become their own graph sensor later.
        if not is_ip(address):
            continue


        try:

            ttl = int(
                record.get("TTL")
                or 0
            )

        except Exception:

            ttl = 0


        current_map[
            address
        ].add(
            hostname
        )


        evidence_key = (
            hostname.lower(),
            address
        )


        current_snapshot.add(
            evidence_key
        )


        # Only insert when a hostname/IP pair
        # appears for the first time in the
        # current in-memory observation state.
        if evidence_key not in dns_snapshot:

            db_execute(
                """
                INSERT INTO dns_evidence
                (
                    session_id,
                    observed_at,
                    hostname,
                    address,
                    ttl,
                    expires_at,
                    source
                )
                VALUES
                (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    SESSION_ID,
                    observed,
                    hostname,
                    address,
                    ttl,
                    current_epoch + ttl,
                    "WINDOWS_DNS_CACHE"
                )
            )


    dns_snapshot = (
        current_snapshot
    )

    dns_map = {
        ip: set(names)
        for ip, names
        in current_map.items()
    }


# ============================================================
# PTR CONTEXT
# ============================================================

ptr_cache = {}


def reverse_dns_worker(ip):

    if ip in ptr_cache:
        return

    try:

        name = socket.gethostbyaddr(
            ip
        )[0].rstrip(".")

    except Exception:

        name = None

    ptr_cache[
        ip
    ] = name


def get_ptr_without_blocking(ip):

    if ip in ptr_cache:

        return (
            ptr_cache[ip],
            ptr_cache[ip] is not None
        )


    # Critical:
    # Never block the 250 ms socket loop
    # waiting for DNS/PTR.
    threading.Thread(
        target=reverse_dns_worker,
        args=(ip,),
        daemon=True
    ).start()


    return (
        None,
        False
    )


# ============================================================
# EVIDENCE SCORE
# ============================================================

def evidence_score(
    process_observed,
    socket_observed,
    forward_dns_observed
):

    score = 0.0

    if process_observed:
        score += 0.35

    if socket_observed:
        score += 0.40

    if forward_dns_observed:
        score += 0.25

    # PTR intentionally contributes nothing.

    return round(
        min(
            score,
            1.0
        ),
        2
    )


# ============================================================
# TLS ACTIVE PROBE
# ============================================================

def tls_probe(
    ip,
    port,
    hostname
):

    if not ACTIVE_PROBES:
        return

    if not TLS_PROBE_ENABLED:
        return

    if port != 443:
        return

    if not safe_for_active_probe(
        ip
    ):
        return


    key = (
        ip,
        port,
        hostname
    )


    with probe_lock:

        if key in tls_probed:
            return

        if (
            len(tls_probed)
            >= MAX_TLS_PROBES
        ):
            return

        tls_probed.add(
            key
        )


    server_name = (
        hostname
        if hostname
        else ip
    )


    try:

        context = (
            ssl.create_default_context()
        )


        with socket.create_connection(
            (
                ip,
                port
            ),
            timeout=PROBE_TIMEOUT
        ) as raw:


            with context.wrap_socket(
                raw,
                server_hostname=server_name
            ) as tls_socket:


                certificate = (
                    tls_socket.getpeercert()
                )


                der = (
                    tls_socket.getpeercert(
                        binary_form=True
                    )
                )


        result = {

            "subject":
                certificate.get(
                    "subject"
                ),

            "issuer":
                certificate.get(
                    "issuer"
                ),

            "subjectAltName":
                certificate.get(
                    "subjectAltName"
                ),

            "serialNumber":
                certificate.get(
                    "serialNumber"
                ),

            "notBefore":
                certificate.get(
                    "notBefore"
                ),

            "notAfter":
                certificate.get(
                    "notAfter"
                )
        }


        if der:

            result[
                "sha256"
            ] = hashlib.sha256(
                der
            ).hexdigest()


        db_execute(
            """
            INSERT INTO probes
            (
                session_id,
                observed_at,
                probe_type,
                remote_ip,
                remote_port,
                hostname_candidate,
                result,
                source
            )
            VALUES
            (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                SESSION_ID,
                utc_now(),
                "TLS_CERTIFICATE",
                ip,
                port,
                hostname,
                json.dumps(
                    result,
                    default=str
                ),
                "ACTIVE_PROBE"
            )
        )


        print(
            "PROBE TLS   "
            f"{ip}:{port} "
            f"SNI={server_name}"
        )


    except Exception:

        pass


# ============================================================
# HTTP ACTIVE PROBE
# ============================================================

def http_probe(
    ip,
    port,
    hostname
):

    if not ACTIVE_PROBES:
        return

    if not HTTP_PROBE_ENABLED:
        return

    if port not in (
        80,
        443
    ):
        return

    if not safe_for_active_probe(
        ip
    ):
        return


    key = (
        ip,
        port,
        hostname
    )


    with probe_lock:

        if key in http_probed:
            return

        if (
            len(http_probed)
            >= MAX_HTTP_PROBES
        ):
            return

        http_probed.add(
            key
        )


    host = (
        hostname
        if hostname
        else ip
    )


    try:

        if port == 443:

            context = (
                ssl.create_default_context()
            )

            connection = (
                http.client.HTTPSConnection(
                    ip,
                    port,
                    timeout=PROBE_TIMEOUT,
                    context=context
                )
            )

        else:

            connection = (
                http.client.HTTPConnection(
                    ip,
                    port,
                    timeout=PROBE_TIMEOUT
                )
            )


        connection.request(
            "HEAD",
            "/",
            headers={
                "Host": host,
                "User-Agent":
                    "MachineObserver/0.6.1"
            }
        )


        response = (
            connection.getresponse()
        )


        result = {

            "status":
                response.status,

            "reason":
                response.reason,

            "headers":
                dict(
                    response.getheaders()
                )
        }


        db_execute(
            """
            INSERT INTO probes
            (
                session_id,
                observed_at,
                probe_type,
                remote_ip,
                remote_port,
                hostname_candidate,
                result,
                source
            )
            VALUES
            (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                SESSION_ID,
                utc_now(),
                "HTTP_HEAD",
                ip,
                port,
                hostname,
                json.dumps(
                    result,
                    default=str
                ),
                "ACTIVE_PROBE"
            )
        )


        print(
            "PROBE HTTP  "
            f"{host} "
            f"{ip}:{port} "
            f"status={response.status}"
        )


        connection.close()


    except Exception:

        pass


# ============================================================
# START ACTIVE PROBES
# ============================================================

def start_probes(
    ip,
    port,
    names
):

    if not ACTIVE_PROBES:
        return


    # Only use hostname when exactly one
    # forward-DNS candidate exists.

    hostname = None


    if len(names) == 1:

        hostname = names[0]


    threading.Thread(
        target=tls_probe,
        args=(
            ip,
            port,
            hostname
        ),
        daemon=True
    ).start()


    threading.Thread(
        target=http_probe,
        args=(
            ip,
            port,
            hostname
        ),
        daemon=True
    ).start()


# ============================================================
# FLOW KEY
# ============================================================

def connection_key(
    connection
):

    return (
        "TCP",
        connection.pid,
        connection.laddr.ip,
        connection.laddr.port,
        connection.raddr.ip,
        connection.raddr.port
    )


# ============================================================
# CREATE FLOW
# ============================================================

def create_flow(
    connection,
    baseline=False
):

    pid = connection.pid

    local_ip = (
        connection.laddr.ip
    )

    local_port = (
        connection.laddr.port
    )

    remote_ip = (
        connection.raddr.ip
    )

    remote_port = (
        connection.raddr.port
    )


    key = connection_key(
        connection
    )


    process = get_process_info(
        pid
    )


    names = sorted(
        dns_map.get(
            remote_ip,
            set()
        )
    )


    forward_dns = (
        len(names) > 0
    )


    reverse_name, reverse_ok = (
        get_ptr_without_blocking(
            remote_ip
        )
    )


    score = evidence_score(
        process[
            "observed"
        ],
        True,
        forward_dns
    )


    flow_id = str(
        uuid.uuid4()
    )


    timestamp = utc_now()


    status = (
        "BASELINE"
        if baseline
        else "OPEN"
    )


    cursor = db_execute(
        """
        INSERT INTO flows
        (
            flow_id,
            session_id,
            first_seen,
            last_seen,
            status,
            close_semantics,
            protocol,
            pid,
            process,
            cmdline,
            local_ip,
            local_port,
            remote_ip,
            remote_port,
            forward_names,
            reverse_name,
            process_observed,
            socket_observed,
            forward_dns_observed,
            reverse_dns_observed,
            evidence_confidence
        )
        VALUES
        (
            ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
            ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
        )
        """,
        (
            flow_id,
            SESSION_ID,
            timestamp,
            timestamp,
            status,
            None,
            "TCP",
            pid,
            process[
                "name"
            ],
            process[
                "cmdline"
            ],
            local_ip,
            local_port,
            remote_ip,
            remote_port,
            (
                " | ".join(names)
                if names
                else None
            ),
            reverse_name,
            int(
                process[
                    "observed"
                ]
            ),
            1,
            int(
                forward_dns
            ),
            int(
                reverse_ok
            ),
            score
        )
    )


    active_flows[
        key
    ] = {

        "db_id":
            cursor.lastrowid,

        "flow_id":
            flow_id,

        "process":
            process[
                "name"
            ],

        "names":
            names,

        "baseline":
            baseline
    }


    if names:

        identity = (
            " | ".join(names)
        )

        source = (
            "FORWARD-DNS"
        )


    elif reverse_name:

        identity = reverse_name

        source = "PTR"


    else:

        identity = (
            "[unknown]"
        )

        source = "NONE"


    print(
        f"{status:<9} "
        f"{timestamp}  "
        f"{process['name']} "
        f"[{pid}]  "
        f"{identity}  "
        f"{local_ip}:{local_port} -> "
        f"{remote_ip}:{remote_port}  "
        f"dns={source} "
        f"evidence={score:.2f}"
    )


    # Don't generate probes for connections
    # that already existed when observer started.

    if not baseline:

        start_probes(
            remote_ip,
            remote_port,
            names
        )


# ============================================================
# INITIAL BASELINE
# ============================================================

def establish_baseline():

    print()
    print(
        "Establishing initial TCP baseline..."
    )


    try:

        connections = (
            psutil.net_connections(
                kind="tcp"
            )
        )

    except psutil.AccessDenied:

        print()
        print(
            "Access denied."
        )

        print(
            "Run PowerShell as Administrator."
        )

        return False


    except Exception as error:

        print(
            "Baseline error:",
            error
        )

        return False


    count = 0


    for connection in connections:

        if (
            connection.status
            != psutil.CONN_ESTABLISHED
        ):
            continue


        if not connection.raddr:
            continue


        if connection.pid is None:
            continue


        create_flow(
            connection,
            baseline=True
        )

        count += 1


    print()

    print(
        f"Baseline established: "
        f"{count} connection(s)"
    )

    print()

    return True


# ============================================================
# LIVE TCP SENSOR
# ============================================================

def scan_tcp():

    current = set()


    try:

        connections = (
            psutil.net_connections(
                kind="tcp"
            )
        )

    except Exception as error:

        print(
            "TCP sensor error:",
            error
        )

        return


    for connection in connections:

        if (
            connection.status
            != psutil.CONN_ESTABLISHED
        ):
            continue


        if not connection.raddr:
            continue


        if connection.pid is None:
            continue


        key = connection_key(
            connection
        )


        current.add(
            key
        )


        if key not in active_flows:

            create_flow(
                connection,
                baseline=False
            )


        else:

            information = (
                active_flows[
                    key
                ]
            )


            # Update PTR later if the
            # background resolver completed.

            remote_ip = key[4]

            ptr = ptr_cache.get(
                remote_ip
            )


            if ptr:

                db_execute(
                    """
                    UPDATE flows

                    SET
                        last_seen=?,
                        reverse_name=?,
                        reverse_dns_observed=1

                    WHERE id=?
                    """,
                    (
                        utc_now(),
                        ptr,
                        information[
                            "db_id"
                        ]
                    )
                )

            else:

                db_execute(
                    """
                    UPDATE flows

                    SET last_seen=?

                    WHERE id=?
                    """,
                    (
                        utc_now(),
                        information[
                            "db_id"
                        ]
                    )
                )


    disappeared = []


    for key, information in list(
        active_flows.items()
    ):

        if key in current:
            continue


        timestamp = utc_now()


        db_execute(
            """
            UPDATE flows

            SET
                last_seen=?,
                status='DISAPPEARED',
                close_semantics=
                    'SNAPSHOT_DISAPPEARANCE'

            WHERE id=?
            """,
            (
                timestamp,
                information[
                    "db_id"
                ]
            )
        )


        (
            protocol,
            pid,
            local_ip,
            local_port,
            remote_ip,
            remote_port
        ) = key


        print(
            "DISAPPEAR "
            f"{timestamp}  "
            f"{information['process']} "
            f"[{pid}]  "
            f"{local_ip}:{local_port} -> "
            f"{remote_ip}:{remote_port}"
        )


        disappeared.append(
            key
        )


    for key in disappeared:

        active_flows.pop(
            key,
            None
        )


# ============================================================
# ACTIVITY CLASSIFIER
# ============================================================

def classify_activity(
    process,
    names,
    remote_port
):

    process_lower = (
        process
        or ""
    ).lower()


    normalized_names = [

        name.lower()

        for name
        in names
    ]


    joined = " ".join(
        normalized_names
    )


    if process_lower == "adb.exe":

        if remote_port == 5555:

            return (
                "Android / ADB",
                "ADB remote-device communication",
                0.95
            )

        return (
            "Android / ADB",
            "ADB communication",
            0.85
        )


    if "tailscale" in process_lower:

        return (
            "Tailscale",
            "Overlay-network communication",
            0.90
        )


    if process_lower in (
        "chrome.exe",
        "msedge.exe",
        "firefox.exe"
    ):

        if (
            "chatgpt.com" in joined
            or "openai.com" in joined
            or "oaiusercontent.com" in joined
        ):

            return (
                "ChatGPT / OpenAI",
                "Browser network activity correlated "
                "with OpenAI hostnames",
                0.90
            )


        if (
            "deepseek.com" in joined
            or "deepseeksvc.com" in joined
        ):

            return (
                "DeepSeek",
                "Browser network activity correlated "
                "with DeepSeek hostnames",
                0.90
            )


        if "github.com" in joined:

            return (
                "GitHub",
                "Browser network activity correlated "
                "with GitHub hostnames",
                0.90
            )


        if normalized_names:

            return (
                "Web browsing",
                "Browser activity with "
                "DNS correlation",
                0.65
            )


        return (
            "Web browsing",
            "Browser activity with "
            "unresolved hostname",
            0.40
        )


    if process_lower in (
        "powershell.exe",
        "pwsh.exe"
    ):

        return (
            "PowerShell",
            "PowerShell-generated network activity",
            0.80
        )


    if process_lower == "explorer.exe":

        return (
            "Windows Explorer",
            "Windows shell network activity",
            0.70
        )


    if process_lower == "svchost.exe":

        return (
            "Windows Service",
            "Windows service-host network activity",
            0.65
        )


    if (
        process
        and process != "unknown"
    ):

        return (
            process,
            "Application network activity",
            0.60
        )


    return (
        "Unknown",
        "Unidentified network activity",
        0.25
    )


# ============================================================
# ACTIVITY ENGINE
# ============================================================

def build_activity_report():

    with db_lock:

        rows = db.execute(
            """
            SELECT
                flow_id,
                pid,
                process,
                remote_ip,
                remote_port,
                forward_names,
                evidence_confidence

            FROM flows

            WHERE session_id=?

            ORDER BY first_seen
            """,
            (
                SESSION_ID,
            )
        ).fetchall()


    activities = defaultdict(
        lambda: {
            "flows": [],
            "processes": set(),
            "pids": set(),
            "hostnames": set(),
            "remote_ips": set(),
            "evidence": [],
            "classification": []
        }
    )


    for row in rows:

        names = []


        if row[
            "forward_names"
        ]:

            names = [

                item.strip()

                for item
                in row[
                    "forward_names"
                ].split("|")

                if item.strip()
            ]


        (
            category,
            meaning,
            class_score
        ) = classify_activity(
            row[
                "process"
            ],
            names,
            row[
                "remote_port"
            ]
        )


        key = (
            category,
            meaning
        )


        activity = (
            activities[
                key
            ]
        )


        activity[
            "flows"
        ].append(
            row[
                "flow_id"
            ]
        )


        if row[
            "process"
        ]:

            activity[
                "processes"
            ].add(
                row[
                    "process"
                ]
            )


        if row[
            "pid"
        ] is not None:

            activity[
                "pids"
            ].add(
                row[
                    "pid"
                ]
            )


        for hostname in names:

            activity[
                "hostnames"
            ].add(
                hostname
            )


        if row[
            "remote_ip"
        ]:

            activity[
                "remote_ips"
            ].add(
                row[
                    "remote_ip"
                ]
            )


        activity[
            "evidence"
        ].append(
            row[
                "evidence_confidence"
            ]
            or 0
        )


        activity[
            "classification"
        ].append(
            class_score
        )


    ordered = sorted(
        activities.items(),
        key=lambda item:
            len(
                item[1][
                    "flows"
                ]
            ),
        reverse=True
    )


    generated = utc_now()


    db_execute(
        """
        DELETE FROM activities
        WHERE session_id=?
        """,
        (
            SESSION_ID,
        )
    )


    for (
        category,
        meaning
    ), activity in ordered:


        evidence_average = (
            sum(
                activity[
                    "evidence"
                ]
            )
            /
            len(
                activity[
                    "evidence"
                ]
            )
        )


        classification_average = (
            sum(
                activity[
                    "classification"
                ]
            )
            /
            len(
                activity[
                    "classification"
                ]
            )
        )


        pids = sorted(
            activity[
                "pids"
            ]
        )


        representative_pid = (
            pids[0]
            if len(pids) == 1
            else None
        )


        db_execute(
            """
            INSERT INTO activities
            (
                session_id,
                generated_at,
                category,
                meaning,
                process,
                pid,
                flow_count,
                hostnames,
                remote_ips,
                evidence_confidence,
                classification_confidence,
                evidence_class
            )
            VALUES
            (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                SESSION_ID,
                generated,
                category,
                meaning,
                ", ".join(
                    sorted(
                        activity[
                            "processes"
                        ]
                    )
                ),
                representative_pid,
                len(
                    activity[
                        "flows"
                    ]
                ),
                " | ".join(
                    sorted(
                        activity[
                            "hostnames"
                        ]
                    )
                ),
                " | ".join(
                    sorted(
                        activity[
                            "remote_ips"
                        ]
                    )
                ),
                round(
                    evidence_average,
                    2
                ),
                round(
                    classification_average,
                    2
                ),
                "INFERRED"
            )
        )


    print()

    print(
        "=" * 72
    )

    print(
        " WHAT IS THIS COMPUTER DOING?"
    )

    print(
        "=" * 72
    )


    if not ordered:

        print(
            "No qualifying TCP activity observed."
        )

        print()

        return


    for (
        category,
        meaning
    ), activity in ordered:


        evidence_average = (
            sum(
                activity[
                    "evidence"
                ]
            )
            /
            len(
                activity[
                    "evidence"
                ]
            )
        )


        classification_average = (
            sum(
                activity[
                    "classification"
                ]
            )
            /
            len(
                activity[
                    "classification"
                ]
            )
        )


        print()

        print(
            f"[{category}]"
        )


        print(
            f"  Meaning : {meaning}"
        )


        print(
            "  Process : "
            +
            (
                ", ".join(
                    sorted(
                        activity[
                            "processes"
                        ]
                    )
                )
                or "[unknown]"
            )
        )


        print(
            f"  Flows   : "
            f"{len(activity['flows'])}"
        )


        print(
            f"  Evidence: "
            f"{evidence_average:.2f}"
        )


        print(
            f"  Inference: "
            f"{classification_average:.2f}"
        )


        if activity[
            "hostnames"
        ]:

            print(
                "  Hosts   : "
                +
                ", ".join(
                    sorted(
                        activity[
                            "hostnames"
                        ]
                    )[:8]
                )
            )


        if activity[
            "remote_ips"
        ]:

            print(
                "  IPs     : "
                +
                ", ".join(
                    sorted(
                        activity[
                            "remote_ips"
                        ]
                    )[:8]
                )
            )


    print()

    print(
        "OBSERVED   = process/socket evidence"
    )

    print(
        "CORRELATED = DNS-supported relationship"
    )

    print(
        "INFERRED   = activity interpretation"
    )

    print(
        "PROBED     = MachineObserver-generated traffic"
    )

    print(
        "UNKNOWN    = insufficient evidence"
    )

    print()


# ============================================================
# SIGNAL HANDLING
# ============================================================

def stop_handler(
    signum,
    frame
):

    global running

    running = False


signal.signal(
    signal.SIGINT,
    stop_handler
)

signal.signal(
    signal.SIGTERM,
    stop_handler
)


# ============================================================
# CLEAN SHUTDOWN
# ============================================================

def clean_shutdown():

    stopped = utc_now()


    for information in list(
        active_flows.values()
    ):

        db_execute(
            """
            UPDATE flows

            SET
                last_seen=?,
                status='OBSERVER_STOPPED',
                close_semantics=
                    'OBSERVER_TERMINATION'

            WHERE id=?
            """,
            (
                stopped,
                information[
                    "db_id"
                ]
            )
        )


    db_execute(
        """
        UPDATE sessions

        SET stopped_at=?

        WHERE session_id=?
        """,
        (
            stopped,
            SESSION_ID
        )
    )


    build_activity_report()


# ============================================================
# MAIN
# ============================================================

def main():

    print()

    print(
        "=" * 72
    )

    print(
        f" MACHINE OBSERVER V{VERSION}"
    )

    print(
        "=" * 72
    )


    # --------------------------------------------------------
    # Migration MUST happen before schema creation.
    # --------------------------------------------------------

    migrate_database()

    init_database()

    start_session()


    print()

    print(
        "OBSERVED   : "
        "Process + PID + CmdLine + TCP"
    )

    print(
        "CORRELATED : "
        "Windows DNS + PTR context"
    )

    print(
        "PROBED     : "
        "TLS certificate + HTTP HEAD"
    )

    print(
        "INFERRED   : "
        "Activity Engine"
    )

    print(
        f"Database   : {DB_PATH}"
    )

    print(
        f"Session    : {SESSION_ID}"
    )

    print(
        f"TCP poll   : {POLL_SECONDS}s"
    )

    print(
        "Ctrl+C to stop"
    )

    print()


    # --------------------------------------------------------
    # DNS BEFORE SOCKET BASELINE
    # --------------------------------------------------------

    print(
        "Reading Windows DNS cache..."
    )

    refresh_dns_cache()

    print(
        f"DNS addresses indexed: "
        f"{len(dns_map)}"
    )


    # --------------------------------------------------------
    # INITIAL SOCKET BASELINE
    # --------------------------------------------------------

    if not establish_baseline():

        raise SystemExit(1)


    last_dns = time.monotonic()

    last_report = time.monotonic()


    try:

        while running:


            current = (
                time.monotonic()
            )


            # ------------------------------------------------
            # DNS REFRESH
            # ------------------------------------------------

            if (
                current
                - last_dns
                >= DNS_REFRESH_SECONDS
            ):

                refresh_dns_cache()

                last_dns = current


            # ------------------------------------------------
            # TCP SENSOR
            # ------------------------------------------------

            scan_tcp()


            # ------------------------------------------------
            # ACTIVITY REPORT
            # ------------------------------------------------

            if (
                current
                - last_report
                >= REPORT_INTERVAL_SECONDS
            ):

                build_activity_report()

                last_report = current


            time.sleep(
                POLL_SECONDS
            )


    except KeyboardInterrupt:

        pass


    finally:

        print()

        print(
            "Stopping Machine Observer..."
        )

        clean_shutdown()

        db.close()

        print()

        print(
            "=" * 72
        )

        print(
            " MACHINE OBSERVER STOPPED"
        )

        print(
            "=" * 72
        )

        print(
            f"Database preserved: "
            f"{DB_PATH}"
        )

        print(
            f"Session: {SESSION_ID}"
        )

        print()


# ============================================================
# ENTRY
# ============================================================

if __name__ == "__main__":

    main()